# Generated by Django 5.0.6 on 2024-09-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomdemo", "0002_product_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(default="Unknown Address", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(
                choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Ms", "Ms")],
                default="Mr",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
