# Generated by Django 5.1.1 on 2024-09-10 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoProject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="expense_type",
            field=models.IntegerField(
                choices=[(0, "Settle Up"), (1, "Expense")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="date_joined",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2024, 9, 10, 17, 39, 36, 770876, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
