# Generated by Django 5.1.1 on 2024-09-10 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoProject", "0002_expense_expense_type_alter_usergroup_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergroup",
            name="date_joined",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2024, 9, 10, 17, 40, 54, 625231, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
